<a href="https://colab.research.google.com/github/irajamuller/data_science/blob/main/Fundamentos_de_Dados_Atividade_Respostas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# 1 - Exercícios sobre a Biblioteca NumPy
---
Observe que cada questão vale 0.2, sendo que o total dessa atividade é 2.0.

Com base no cenário a seguir, responda o que se pede.


In [ ]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

### 1.1 - Considere as duas matrizes acima $A$ e $B$ e calcule a transposta de A e B. A transposta de uma matriz é representada por $A^T$.

In [ ]:
print('Transposta de A\n', A.T)
print('Transposta de B\n', B.T)

Transposta de A
 [[1 3]
 [2 4]]
Transposta de B
 [[5 7]
 [6 8]]


### 1.2 - Considere as duas matrizes acima  $A$  e  $B$ e calcule o produto matricial $A$ e $B$ usando @ (produto de matrizes).

In [ ]:
print('A.B\n', A @ B)

A.B
 [[19 22]
 [43 50]]


### 1.3 - Considere as duas matrizes acima  $A$ e $B$ e calcule o produto matricial da $A^T$ x $B$ e $A$ x $B^T$.

In [ ]:
print('A^T.B\n', A.T @ B)
print('A.B^T\n', A @ B.T)


A^T.B
 [[26 30]
 [38 44]]
A.B^T
 [[17 23]
 [39 53]]


---
# 2 - Exercícios sobre a Biblioteca Pandas
---
Com base na descrição do dataset <strong>penguins</strong> presente na biblioteca Seaborn, responda o que se pede.

| Atributo            | Tipo             | Descrição                                                            |
| ------------------- | ---------------- | -------------------------------------------------------------------- |
| `species`           | Categórico       | Espécie do pinguim (`Adelie`, `Chinstrap` ou `Gentoo`)               |
| `island`            | Categórico       | Ilha onde o pinguim foi observado (`Biscoe`, `Dream` ou `Torgersen`) |
| `bill_length_mm`    | Numérico (float) | Comprimento do bico em milímetros                                    |
| `bill_depth_mm`     | Numérico (float) | Profundidade do bico em milímetros                                   |
| `flipper_length_mm` | Numérico (int)   | Comprimento da nadadeira em milímetros                               |
| `body_mass_g`       | Numérico (int)   | Massa corporal em gramas                                             |
| `sex`               | Categórico       | Sexo do pinguim (`Male`, `Female`)                                   |
| `year`              | Numérico (int)   | Ano em que a observação foi feita (`2007`, `2008`, `2009`)           |


In [ ]:
import seaborn as sns
import pandas as pd

# Carregamento do dataset
df = sns.load_dataset("penguins")

### 2.1 - Quantos pinguins pertencem à espécie Adelie?

In [ ]:
len(df[df['species'] == 'Adelie'])

152

### 2.2 - Quais são as espécies únicas de pinguins?

In [ ]:
print(df['species'].unique())

['Adelie' 'Chinstrap' 'Gentoo']


### 2.3 - Mostre os pinguins com massa corporal acima de 5000g.

In [ ]:
df[df['body_mass_g'] > 5000]

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
221  Gentoo  Biscoe            50.0           16.3              230.0   
223  Gentoo  Biscoe            50.0           15.2              218.0   
224  Gentoo  Biscoe            47.6           14.5              215.0   
227  Gentoo  Biscoe            46.7           15.3              219.0   
229  Gentoo  Biscoe            46.8           15.4              215.0   
..      ...     ...             ...            ...                ...   
335  Gentoo  Biscoe            55.1           16.0              230.0   
337  Gentoo  Biscoe            48.8           16.2              222.0   
341  Gentoo  Biscoe            50.4           15.7              222.0   
342  Gentoo  Biscoe            45.2           14.8              212.0   
343  Gentoo  Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
221       5700.0    Male  
223       5700.0    Male  
224       5400.0    Male  
227       5200.0    Male  
229       5150.0    Male  
..           ...     ...  
335       5850.0    Male  
337       6000.0    Male  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[61 rows x 7 columns]

### 2.4 - Qual o peso médio dos pinguins da ilha Biscoe?

In [ ]:
print(df[df['island'] == 'Biscoe']['body_mass_g'].mean())

4716.017964071856


### 2.5 - Qual o maior comprimento do bico?

In [ ]:
df['bill_length_mm'].max()

59.6

### 2.6 - Qual a média do comprimento da nadadeira dos machos da ilha Dream?

In [ ]:
print(df.query('sex == "Male" and island == "Dream"')['flipper_length_mm'].mean())
# ou print(df[(df['sex'] == 'Male') & (df['island'] == 'Dream')]['flipper_length_mm'].mean())

196.30645161290323


### 2.7 - Quais são os 5 pinguins mais pesados?

In [ ]:
# Primeiro ordena decrescente e depois mostra somente os 5 primeiros
df.sort_values('body_mass_g', ascending=False).head(5)

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
237  Gentoo  Biscoe            49.2           15.2              221.0   
253  Gentoo  Biscoe            59.6           17.0              230.0   
337  Gentoo  Biscoe            48.8           16.2              222.0   
297  Gentoo  Biscoe            51.1           16.3              220.0   
299  Gentoo  Biscoe            45.2           16.4              223.0   

     body_mass_g   sex  
237       6300.0  Male  
253       6050.0  Male  
337       6000.0  Male  
297       6000.0  Male  
299       5950.0  Male